{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "github-actions-runner.fullname" . }}
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "github-actions-runner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: "{{ .Values.serviceAccount.roleName }}"
  apiGroup: rbac.authorization.k8s.io
{{- end }}
