---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "github-actions-runner.fullname" . }}-entrypoint
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
data:
  {{ .Files.AsConfig "files/*.sh" | nindent 2 }}
