{{- if .Values.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "github-actions-runner.fullname" . }}{{- with .Values.secrets.RUNNER_TOKEN }}-{{ . | sha1sum }}{{- end }}
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
  {{- if ne .Values.persistentVolume.storageClassName "" }}
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  {{- end }}
{{- end }}
