{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-actions-runner.fullname" . }}
  labels:
{{- include "github-actions-runner.labels" . | nindent 4 }}
data:
  {{- range $name, $value := .Values.secrets }}
  {{ $name }}: "{{ tpl $value $ | b64enc }}"
  {{- end }}
{{- end }}
