apiVersion: v1
kind: Service
metadata:
  name: {{ include "github-actions-runner.fullname" . }}
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
