---
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ template "github-exporter.fullname" . }}
  labels:
  {{- include "github-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "github-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- . | nindent 8 }}
      {{- end }}
      labels:
      {{- include "github-exporter.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: github-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion  }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9171
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: GITHUB_EXPORTER_PORT
              value: "9171"
            {{- range $name, $value := .Values.env }}
            - name: {{ $name | quote }}
              value: {{ tpl $value $ | quote }}
            {{- end }}
            {{- range $name, $value := .Values.secrets }}
            - name: {{ $name | quote }}
              valueFrom:
                secretKeyRef:
                  name: "{{ template "github-exporter.fullname" $ }}"
                  key: {{ $name | quote }}
            {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- with .Values.extraVolumeMounts }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
      volumes:
        {{- with .Values.extraVolumes }}
        {{- tpl . $ | nindent 8 }}
        {{- end }}
      serviceAccountName: {{ include "github-exporter.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
  {{- end }}
