name: Chart Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.8.1

      - name: Run chart-releaser
        id: changes
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_packaging: true
          skip_upload: true

      - name: Bump version
        if: ${{ steps.changes.changed_charts != '' }}
        run: |
          for chart in ${changes_charts//,/ }; do
              cd "$GITHUB_WORKSPACE/charts/$chart"

              LATEST_VERSION=$(git for-each-ref --sort=creatordate --format '%(refname:lstrip=2)' "refs/tags/${chart}-\*" | tail -n 1 | grep -o '[^-]*$')
              if [ "${LATEST_VERSION}" == "" ]; then
                  echo "Could not find latest tag for chart. Using 0.0.0"
                  LATEST_VERSION=0.0.0
                  NEXT_VERSION=0.1.0
              else
                  COMMITS_SINCE_LATEST_TAG=$(git log refs/tags/${chart}-${LATEST_VERSION}..HEAD --oneline)
                  if [ "${COMMITS_SINCE_LATEST_TAG}" == "" ]; then
                      NEXT_VERSION=0.1.0
                  fi

                  PR_LABELS=$(gh pr list --search "996078e666b1db7de82bf74bc89df6c2b830c308" --state merged --json labels)

              fi
          done
        env:
          changes_charts: "${{ steps.changes.changed_charts }}"

      - name: Run chart-releaser
        if: ${{ steps.changes.changed_charts != '' }}
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Login to GitHub Container Registry
        if: ${{ steps.changes.changed_charts != '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Charts to GHCR
        if: ${{ steps.changes.changed_charts != '' }}
        run: |
          shopt -s nullglob
          for pkg in .cr-release-packages/*; do
            if [ -z "${pkg:-}" ]; then
              break
            fi
            if ! helm push "${pkg}" "oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts"; then
              echo '::warning:: helm push failed!'
            fi
          done

          grep -o '[^,]*$'
